/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package page;

import Class.History;
import Class.User;
import Service.LobbyService;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import layout.HistoryItem;
import layout.RankItem;
import layout.UserListItem;

/**
 *
 * @author MYSNACK
 */
public class FormLobby extends javax.swing.JFrame {

    String username;
    User player;
    User user;
    ArrayList<User> userArr;
    ArrayList<History> history;
    private int xMouse, yMouse;

    /**
     * Creates new form FormLobby
     */
    public FormLobby() {
        initComponents();
    }

    public FormLobby(String username) {
        initComponents();
        this.username = username;
        User user = LobbyService.getUser("supisara1511");
        listshow.setVisible(true);
        listRank.setVisible(false);
        userArr = LobbyService.getPlaerAll();
        history = LobbyService.getHistory(this.username);
        System.out.println(history);
        labelName.setText(labelName.getText() + " " + user.getName());
        labelUsername.setText(labelUsername.getText() + " " + user.getUsername());
        ListPlayer.setBackground(new Color(53, 28, 14));
        int y = 0;
        for (User userItem : userArr) {
            System.out.println(userItem.getUserID());
            ListPlayer.add(new UserListItem(userItem, 0, y));
            y += 50;
            ListPlayer.revalidate();
            ListPlayer.repaint();
        }

        int p = 0;
        for (History his : history) {
            listshow.add(new HistoryItem(his, 0, p));
            p += 50;
            listshow.revalidate();
            listshow.repaint();

        }

        int u = 0;
        int i = 1;
        for (User rank : userArr) {
            listRank.add(new RankItem(rank, 0, u, i));
            u += 50;
            listRank.revalidate();
            listRank.repaint();
            i++;

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        listRank = new javax.swing.JPanel();
        listshow = new javax.swing.JPanel();
        buttonRanking = new javax.swing.JLabel();
        buttonHistory = new javax.swing.JLabel();
        ListPlayer = new javax.swing.JPanel();
        button_close = new javax.swing.JLabel();
        labelUsername = new javax.swing.JLabel();
        labelName = new javax.swing.JLabel();
        buttonsearch = new javax.swing.JLabel();
        textboxSearch = new javax.swing.JTextField();
        bg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1024, 768));
        setMinimumSize(new java.awt.Dimension(1024, 768));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(1024, 768));
        getContentPane().setLayout(null);

        listRank.setOpaque(false);
        listRank.setLayout(null);
        getContentPane().add(listRank);
        listRank.setBounds(394, 260, 600, 480);

        listshow.setOpaque(false);
        listshow.setLayout(null);
        getContentPane().add(listshow);
        listshow.setBounds(394, 260, 600, 480);

        buttonRanking.setIcon(new javax.swing.ImageIcon("C:\\Users\\MYSNACK\\Desktop\\New folder\\xogame_g2-2\\src\\imgs\\buttonRanking02.png")); // NOI18N
        buttonRanking.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonRankingMouseClicked(evt);
            }
        });
        getContentPane().add(buttonRanking);
        buttonRanking.setBounds(696, 200, 330, 40);

        buttonHistory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/buttonHistory01.png"))); // NOI18N
        buttonHistory.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonHistoryMouseClicked(evt);
            }
        });
        getContentPane().add(buttonHistory);
        buttonHistory.setBounds(368, 200, 330, 40);

        ListPlayer.setToolTipText("");
        ListPlayer.setAutoscrolls(true);
        ListPlayer.setOpaque(false);
        ListPlayer.setLayout(null);
        getContentPane().add(ListPlayer);
        ListPlayer.setBounds(30, 150, 300, 590);

        button_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bt-close.png"))); // NOI18N
        button_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                button_closeMouseClicked(evt);
            }
        });
        getContentPane().add(button_close);
        button_close.setBounds(980, 10, 30, 30);

        labelUsername.setFont(new java.awt.Font("PSLxOmyim", 0, 24)); // NOI18N
        labelUsername.setForeground(new java.awt.Color(255, 255, 255));
        labelUsername.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelUsername.setToolTipText("");
        getContentPane().add(labelUsername);
        labelUsername.setBounds(520, 80, 320, 50);

        labelName.setFont(new java.awt.Font("PSLxOmyim", 0, 48)); // NOI18N
        labelName.setForeground(new java.awt.Color(255, 255, 255));
        labelName.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelName.setText("Hi,");
        labelName.setToolTipText("");
        getContentPane().add(labelName);
        labelName.setBounds(520, 40, 320, 50);

        buttonsearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/Icon_Scan_1.png"))); // NOI18N
        buttonsearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buttonsearchMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buttonsearchMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buttonsearchMouseExited(evt);
            }
        });
        getContentPane().add(buttonsearch);
        buttonsearch.setBounds(280, 100, 30, 40);

        textboxSearch.setBorder(null);
        getContentPane().add(textboxSearch);
        textboxSearch.setBounds(50, 103, 220, 30);

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgs/bgLabby.png"))); // NOI18N
        bg.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                bgMouseDragged(evt);
            }
        });
        bg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bgMousePressed(evt);
            }
        });
        getContentPane().add(bg);
        bg.setBounds(0, 0, 1024, 768);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonsearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearchMouseClicked
        String searchUser = textboxSearch.getText();
        if (searchUser.isEmpty()) {
            player = LobbyService.searchPlayer(searchUser);
        }
    }//GEN-LAST:event_buttonsearchMouseClicked

    private void buttonsearchMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearchMouseEntered
        ImageIcon img = new ImageIcon(this.getClass().getResource("../imgs/Icon_Scan_1.png"));
        buttonsearch.setIcon(img);
    }//GEN-LAST:event_buttonsearchMouseEntered

    private void buttonsearchMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonsearchMouseExited
        ImageIcon img = new ImageIcon(this.getClass().getResource("../imgs/Icon_Scan_2.png"));
        buttonsearch.setIcon(img);
    }//GEN-LAST:event_buttonsearchMouseExited

    private void button_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_button_closeMouseClicked
        System.exit(0);
    }//GEN-LAST:event_button_closeMouseClicked

    private void bgMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_bgMousePressed

    private void bgMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bgMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_bgMouseDragged

    private void buttonHistoryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonHistoryMouseClicked
        ImageIcon img1 = new ImageIcon(this.getClass().getResource("../imgs/buttonHistory01.png"));
        buttonHistory.setIcon(img1);

        ImageIcon img2 = new ImageIcon(this.getClass().getResource("../imgs/buttonRanking02.png"));
        buttonRanking.setIcon(img2);
        
        listshow.setVisible(true);
        listRank.setVisible(false);

    }//GEN-LAST:event_buttonHistoryMouseClicked

    private void buttonRankingMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buttonRankingMouseClicked
        ImageIcon img1 = new ImageIcon(this.getClass().getResource("../imgs/buttonHistory02.png"));
        buttonHistory.setIcon(img1);

        ImageIcon img2 = new ImageIcon(this.getClass().getResource("../imgs/buttonRanking01.png"));
        buttonRanking.setIcon(img2);
        
        listshow.setVisible(false);
        listRank.setVisible(true);
        
        
        
    }//GEN-LAST:event_buttonRankingMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLobby.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLobby().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel ListPlayer;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel buttonHistory;
    private javax.swing.JLabel buttonRanking;
    private javax.swing.JLabel button_close;
    private javax.swing.JLabel buttonsearch;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelUsername;
    private javax.swing.JPanel listRank;
    private javax.swing.JPanel listshow;
    private javax.swing.JTextField textboxSearch;
    // End of variables declaration//GEN-END:variables
}
